name: 'Build and publish npm package'

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  build_publish:
    name: Build and publish npm package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run pretty

      - name: Run tests
        run: npm run test

      - name: Build package
        run: npm run build

      - name: Publish package to npm
        id: publish
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Update scope name in package json file for GitHub
        uses: restack/update-json-values-action@v1.0.0
        with:
          file: package.json
          values: "{'@clydedsouza/horoscope': '@clydedz/horoscope'}"

      - name: Publish package to GitHub
        id: publishgithub
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: 'https://npm.pkg.github.com'

      - if: ${{ steps.publish.outputs.type }}
        run: |
          echo "Version changed!"
